# Generated by Django 3.2.9 on 2021-11-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('attribution', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Office',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date_join', models.DateField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_code', models.IntegerField()),
                ('description', models.TextField()),
                ('premium', models.CharField(max_length=50)),
                ('allocation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField()),
                ('request_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('method_of_cancellation', models.CharField(max_length=50)),
                ('beneficiary_id', models.IntegerField()),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.service')),
            ],
            options={
                'verbose_name_plural': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SubscriptionType',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('employer_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User Info',
            },
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.IntegerField()),
                ('transfer_from', models.CharField(max_length=100)),
                ('transfer_to', models.CharField(max_length=100)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.subscriber')),
            ],
            options={
                'verbose_name_plural': 'TransferredSubscription',
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.userinfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('native_country', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=30)),
                ('is_delegate', models.BooleanField(default=False)),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.organization')),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.subscriber')),
            ],
            options={
                'verbose_name_plural': 'OrganizationMember',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('office_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.office')),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synd.subscriber')),
            ],
            options={
                'verbose_name_plural': 'Officer',
            },
        ),
    ]
